# ~/.config/starship.toml

# General
command_timeout = 3000

[username]
format = "[$user]($style)@"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
format = "[$path]($style) [$read_only]($read_only_style) "

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "✗"

[status]
symbol = "🔴"
sigint_symbol = "❗"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[shell]
unknown_indicator = "mystery shell"
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true
