# ~/.config/starship.toml

# General
command_timeout = 3000
right_format = """$time"""
continuation_prompt = "  [↪](bold yellow)  "

[username]
format = "[$user]($style)@"
# style_user = "bold #bd93f9" # Dracula

# [hostname]
# style = "bold #ff5555" # Dracula

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
# success_symbol = "[➜](bold #f8f8f2)" # Dracula
# error_symbol = "[➜](bold #ff5555)" # Dracula


[directory]
format = "[$path]($style) [$read_only]($read_only_style) "
# style = "bold #50fa7b" # Dracula

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
# style = "bold #f1fa8c" # Dracula

[memory_usage]
disabled = true
threshold = -1
symbol = "𝐑𝐀𝐌 "
style = "bold dimmed green"
format = "$fill $symbol [${ram_pct}]($style) "

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "✗"
# style = "bold #ff5555" # Dracula

[git_branch]
# style = "bold #ff79c6" # Dracula

[status]
symbol = "🔴 "
sigint_symbol = "❗"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[shell]
unknown_indicator = "mystery shell"
disabled = true

[aws]
# style = "bold #ffb86c" # Dracula
disabled = true

[gcloud]
disabled = true
